### ISSUE TITLE
Raise ValueError when running play_vid mode

### ISSUE THREAD

**Issue by nvidiafucku** [yoterel/nepmap#1]
Following README.md, I ran the code below:

Stream a movie onto the Castle scene:
`python train.py --config configs/castle.txt --render_only --render_modes play_vid`

But this was terminated with following traceback:

```
Traceback (most recent call last):
  File "/home/admin/projects/nepmap/nepmap-server/train.py", line 384, in <module>
    render_sandbox(radiance_field, occupancy_grid, scene_aabb,
  File "/home/admin/projects/nepmap/nepmap-server/helpers.py", line 1412, in render_sandbox
    reader = VideoReader(Path(extra_info["vid_path"]),
  File "/home/admin/local/mambaforge/envs/nepmap1/lib/python3.9/site-packages/gsoup/video.py", line 231, in __init__
    raise ValueError("target resolution must have common divisor with original resolution")
```

The version of the packages I use:
- python:  3.9.18 
- gsoup: 0.0.8

**Comment by yoterel** [comment]
Hi there, thanks for the feedback !
When we load a video it is resized to fit the projector resolution used for training. 
however, I was using a naive resizing approach so the video didn't work. Now we use the opencv resizing method.

1) please pull the changes
2) please uninstall gsoup and opencv-contrib-python, and then reinstall gsoup (the latest version is 0.2.3)

the reason to unisntall opencv-contrib-python, is because the new gsoup versions use opencv-python which conflicts with opencv-contrib-python.

(please reopen if this doesn't work out, I ran this on my setup and it worked)
